### ISSUE TITLE
Error in cake Sb.Shell mvc command 

### ISSUE THREAD

**Issue by pratiksha2211** [el-cms/superBake#43]
Hello 
I have followed all instruction but while gave commnad to create MVC like

cake Sb.Shell mvc 

It shows error like and 

You can download PHPUnit from http://phpunit.de

Baking test fixture for Post...

Creating file C:\wamp\www\cakephp243\app\Plugin\Blog\Test\Fixture\PostFixture.ph
p
Wrote `C:\wamp\www\cakephp243\app\Plugin\Blog\Test\Fixture\PostFixture.php`
Bake is detecting possible fixtures...
Error: Plugin Misc could not be found.
#0 C:\wamp\www\cakephp\lib\Cake\Core\App.php(365): CakePlugin::path('Misc')
#1 C:\wamp\www\cakephp\lib\Cake\Core\App.php(226): App::pluginPath('Misc')
#2 C:\wamp\www\cakephp\lib\Cake\Core\App.php(547): App::path('Model', 'Misc')
#3 [internal function]: App::load('License').

Please help me to solve this 

Thanks in advance

**Comment by mtancoigne** [comment]
Hi !

It looks like the "misc" plugin is missing, so there are two cases: it's actually missing, or it was created but not enabled in the app's bootstrap file.

When you first created the plugins structures (`Sb.Shell plugins`), have you aswered 'y' when the shell asked for the update of the bootstrap file ? If no, you can run it again, it will update it.

**Comment by pratiksha2211** [comment]
Hello 

Thanks for reply 

What is misk plugin ? Where was misc plugin in my cakephp folder ?, Is it require in super bake ? 

There are no misc plugin in my folder 

And yes , I answered Yes in first command  (Sb.Shell plugins). And It Successfully Created Blog Folder in plugins.

Thanks

**Comment by mtancoigne** [comment]
... superBake is a tool to batch generate an app MVC. In the version you downloaded, the sample configuration file works with the sample DB model (in docs). It describes an application that have several plugins (blog, gallery, projects,... and a "misc" plugins with license management and other little things. )

I tried on a fresh install too, and can't figure what's wrong... After plugins generation, do you have the differents plugins in "app/plugins" ?

Can you restart from the begining ? delete all folders in `<cake php install>app/plugins`, edit the file `app/Config/bootstrap.php` and remove all the `CakePlugin::Load()` that are not `CakePlugin::Load('Sb'...)`. Then relaunch `Sb.Shell plugins` and send me the output.

**Comment by pratiksha2211** [comment]
No , I only have Blog plugins in app/plugins.

I have configure cakephp 2.4.3 as describe in readme file .

Should i require to add misc plugin ?

How can add it ?

Thanks

**Comment by pratiksha2211** [comment]
Hello 

I got following output

```
Welcome to CakePHP v2.4.3 Console
---------------------------------------------------------------
App : app
Path: C:\wamp\www\cakephp243\app\
---------------------------------------------------------------

-[ I ]---------------------------------------------------------


  >  Building all plugins structures


---------------------------------------------------------------

Do we have to update the app's bootstrap file ? (y/n)
[y] > y


-[ I ]---------------------------------------------------------
  >  Building Blog
---------------------------------------------------------------
  >  The "Blog" plugin will be created in the "C:\wamp\www\cakephp243\app\Plugin
\" dir.

Creating file C:\wamp\www\cakephp243\app\Plugin\Blog\Controller\BlogAppControlle
r.php
Wrote `C:\wamp\www\cakephp243\app\Plugin\Blog\Controller\BlogAppController.php`

Creating file C:\wamp\www\cakephp243\app\Plugin\Blog\Model\BlogAppModel.php
Wrote `C:\wamp\www\cakephp243\app\Plugin\Blog\Model\BlogAppModel.php`
  >  C:\wamp\www\cakephp243\app\Config\bootstrap.php modified
  *  Plugin created

/////////////////////////////////\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\

  #  There was no plugins to generate.
```

Edit from Manuel Tancoigne: updated with code block

**Comment by mtancoigne** [comment]
Can you open a browser at `<yourCakeinstall>/sb/sb/tree` and have a look at the plugin list.
You should have something like this:
![2014-01-31 14_48_19-superbake_ sb - nightly](https://f.cloud.github.com/assets/1732268/2050887/74128c90-8a7e-11e3-9d03-c88d7af21813.png)

Because your issue is weird : you have only the blog plugin being generated, but when you want to bake the mvc, superBake finds the others plugins...

**Comment by pratiksha2211** [comment]
I had open browser in as you said and got following page 

![superbake- sb 2014-01-31 19-37-58](https://f.cloud.github.com/assets/5039554/2051004/21e41508-8a81-11e3-8417-3baf5c85c14c.png)

**Comment by mtancoigne** [comment]
I wonder wich version you are using, as the configuration file containing parts "EmptyForTest" or "Lols" is away since a long time... Is it the last version ?

You can download it again here https://github.com/el-cms/superBake/archive/0.3-alpha.zip

**Comment by mtancoigne** [comment]
Does it works with the new version ?

**Comment by mtancoigne** [comment]
Closed as the problem seems to be related to an older commit.

**Comment by pratiksha2211** [comment]
Hello ,

Yes It was work with new plugin , but when run in browser there was no template showing, only menu working as listing all plugins , And also admin not working.... 
Should i need to add any template in this ?

please help me

**Comment by mtancoigne** [comment]
Hi !
I provide sample DB and config file to test superBake. That's for test only as superbake is in development.
What are you trying to do with it and what to you expect from it, exactly ? If you want something that works "out of the box", then superBake is not such a tool. it's here to help developpers in the development process of their applications, but not meant to provide a complete cms or website.

Your question in vague, as I don't know the error and what you are doing, or trying to do.

Please, be more specific and i'll be happy to help :)
